server:
    bind:
        host: 0.0.0.0
        port: 80
    url: https://apisandbox.geonovum.nl/pygeoapi_SU
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    language: en-US
    cors: true
    pretty_print: true
    limit: 500
    map:
        url: https://service.pdok.nl/brt/achtergrondkaart/wmts/v2_0/standaard/EPSG:3857/{z}/{x}/{y}.png
        attribution: 'Map data &copy; <a href="https://pdok.nl">PDOK Kadaster</a>'
#        url: https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png
#        attribution: '<a href="https://wikimediafoundation.org/wiki/Maps_Terms_of_Use">Wikimedia maps</a> | Map data &copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    ogc_schemas_location: /schemas.opengis.net

logging:
    level: ERROR
    #logfile: /tmp/master.log

metadata:
    identification:
        title: GeoNovum OGC API testbed Statistical Units
        description: An implementation showing use of pygeoapi as INSPICE download service
        keywords:
            - geospatial
            - data
            - INSPIRE
            - Download service
            - api
            - Statitical Units
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/3.0/
        url: https://www.nationaalgeoregister.nl/geonetwork/srv/dut/catalog.search#/metadata/10d1153e-778f-4995-9b6c-7c69b196cccb
    license:
        name: CC-BY 3.0 license
        url: http://creativecommons.org/licenses/by/3.0/nl/
    provider:
        name: CBS
        url: https://www.cbs.nl
    contact:
        name: CBS - Infoservice
        position: Helpdesk
        address: 
        city: Den Haag
        stateorprovince: Zuid Holland
        postalcode: 
        country: The Netherlands
        phone: 
        fax: 
        email: info@cbs.nl
        url: https://www.cbs.nl
        role: pointOfContact

resources:
    StatisticalUnits_Gemeente:
        type: collection
        title: StatisticalUnits_Gemeente
        description: In deze dataset zijn de begrenzingen opgenomen van Nederlandse Gemeenten. De gegevens in de dataset zijn conform INSPIRE geharmoniseerd.
        keywords:
            - statistiek
            - Gemeenten
        crs:
            - EPSG:4258
        links:
            - type: text/html
              rel: describedby
              title: Metadata as HTML
              href: https://www.nationaalgeoregister.nl/geonetwork/srv/dut/catalog.search#/metadata/10d1153e-778f-4995-9b6c-7c69b196cccb
              hreflang: nl
            - type: application/xml
              rel: describedby
              title: Metadata as iso19139 xml
              href: https://www.nationaalgeoregister.nl/geonetwork/srv/metadata/10d1153e-778f-4995-9b6c-7c69b196cccb/formatters/xml
              hreflang: nl
            - type: text/html
              rel: tag
              title: Referentie naar het concept beschermde gebieden (inspire registry)
              href: https://inspire.ec.europa.eu/featureconcept/VectorStatisticalUnit
              hreflang: nl
            - type: application/gml+xml
              rel: enclosure
              title: Download volledige dataset als GML
              href: http://geodata.nationaalgeoregister.nl/su-vector/wfs?request=GetFeature&version=2.0.0&typeNames=su-vector:AreaStatisticalUnit&filter=%3CFilter+xmlns=%22http://www.opengis.net/ogc%22%3E%3CPropertyIsEqualTo%3E%3CPropertyName%3Esu-vector%3Atesselation%2Fsu-vector%3AStatisticalTessellation%2Fsu-vector%3AinspireId%2Fbase33%3AIdentifier%2Fbase33%3AlocalId%3C/PropertyName%3E%3CLiteral%3Egemeente.2018%3C/Literal%3E%3C/PropertyIsEqualTo%3E%3C/Filter%3E
              hreflang: nl
        extents:
            spatial:
                bbox: [3.10, 50.50, 7.60, 53.80]
                crs: http://www.opengis.net/def/crs/OGC/1.3/EPSG:4258
            temporal:
                begin: 2018-01-01T00:00:01Z  # start datetime in RFC3339
                end: 2018-12-31T23:59:59Z  # end datetime in RFC3339
        providers:
            - type: feature
              name: OGR
              data:
                  source_type: GPKG
                  source: data/SU_NL_ETRS89.gpkg
                  source_srs: EPSG:4258
                  target_srs: EPSG:4326
                  source_capabilities:
                      paging: True

                  gdal_ogr_options:
                      EMPTY_AS_NULL: NO
                      GDAL_CACHEMAX: 64
                      # GDAL_HTTP_PROXY: (optional proxy)
                      # GDAL_PROXY_AUTH: (optional auth for remote WFS)
                      CPL_DEBUG: NO

              id_field: localid
              title_field: geographicalname
              layer: su_gemeente_2018
