server:
    bind:
        host: 0.0.0.0
        port: 80
    url: https://apisandbox.geonovum.nl/pygeoapi_luchtmeetnet
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    language: en-US
    cors: true
    pretty_print: true
    limit: 100
    map:
        url: https://service.pdok.nl/brt/achtergrondkaart/wmts/v2_0/standaard/EPSG:3857/{z}/{x}/{y}.png
        attribution: 'Map data &copy; <a href="https://pdok.nl">PDOK Kadaster</a>'
#        url: https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png
#        attribution: '<a href="https://wikimediafoundation.org/wiki/Maps_Terms_of_Use">Wikimedia maps</a> | Map data &copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    ogc_schemas_location: /schemas.opengis.net

logging:
    level: ERROR
    #logfile: /tmp/master.log

metadata:
    identification:
        title: GeoNovum OGC API testbed Luchtmeetnet
        description: Stations from RIVMs Luchtmeetnet API for demonstration purposes
        keywords:
            - geospatial
            - demonstration
            - Luchtmeetnet
            - air quality
            - measurement stations
            - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://api-docs.luchtmeetnet.nl/
    license:
        name: CC-BY 4.0 license
        url: http://creativecommons.org/licenses/by/4.0/
    provider:
        name: Geonovum API Testbed
        url: https://www.geonovum.nl
    contact:
        name: Geonovum API Testbed
        position: Helpdesk
        address: Barchman Wuytierslaan 10
        city: Amersfoort
        stateorprovince: Utrecht
        postalcode: 3818 LH
        country: The Netherlands
        # phone: +31 633 4217456
        # fax: +31 633 4217799
        email: info@geonovum.nl
        url: https://www.geonovum.nl
        role: pointOfContact

resources:
    stations:
        type: collection
        title: Luchtmeetnet stations
        description: Stations taken from the Luchtmeetnet API of RIVM, https://api-docs.luchtmeetnet.nl. This collection is for demonstration purposes only, to publish the stations through OGC API Features for the API Testbed of Geonovum. Please use the Luchtmeetnet API directly if you are not involved in the Geonovum API Testbed.
        keywords:
            - Luchtmeetnet
            - Stations
            - demonstration
        crs:
            - EPSG:4326
        links:
            - type: text/html
              rel: describedby
              title: Original API documentation Luchtmeetnet
              href: https://api-docs.luchtmeetnet.nl/#intro
              hreflang: nl
        extents:
            spatial:
                bbox: [3.74, 50.84, 6.94, 53.34]
                crs: http://www.opengis.net/def/crs/OGC/1.3/EPSG:4326
            temporal:
                begin:
                end: null  # or empty
        providers:
            - type: feature
              name: GeoJSON
              data: data/stations.json
              id_field: number
